baseURL = "https://islash8.github.io/"
languageCode = "en-us"
title = "Islash8"
theme = "archie-master"
copyright = "© Islash8"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname"  # Set your Disqus shortname if you want to use Disqus comments

paginate = 5 # articles per page

[params]
	mode = "toggle"  # color-mode → light, dark, toggle, or auto
	useCDN = false  # don't use CDNs for fonts and icons, instead serve them locally
	# subtitle = "A personal blog about technology, career, books, and life."
	mathjax = true  # enable MathJax support
	katex = true  # enable KaTeX support

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/islash8"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/islash8_"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/islash8/"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
